-- Master table: inventory item types (managed by admin)
CREATE TABLE public.inventory_item_types (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(256) NOT NULL UNIQUE,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.inventory_item_types ENABLE ROW LEVEL SECURITY;

-- Everyone can read item types
CREATE POLICY "inventory_item_types_select" ON public.inventory_item_types
  FOR SELECT USING (true);

-- Only admin/contributor can manage master data
CREATE POLICY "inventory_item_types_insert" ON public.inventory_item_types
  FOR INSERT WITH CHECK (public.is_contributor_or_admin());

CREATE POLICY "inventory_item_types_update" ON public.inventory_item_types
  FOR UPDATE USING (public.is_contributor_or_admin());

CREATE POLICY "inventory_item_types_delete" ON public.inventory_item_types
  FOR DELETE USING (public.is_admin());

-- Seed common liturgical items
INSERT INTO public.inventory_item_types (name) VALUES
  ('Cáliz'),
  ('Patena'),
  ('Florero'),
  ('Biblia'),
  ('Atril'),
  ('Menorá'),
  ('Candelabro'),
  ('Cruz'),
  ('Mantel'),
  ('Ambón'),
  ('Micrófono'),
  ('Cirio Pascual'),
  ('Icono');

-- Audit trigger for master table
CREATE TRIGGER audit_inventory_item_types
  AFTER INSERT OR UPDATE OR DELETE ON public.inventory_item_types
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();

-- Community inventory: items per community
CREATE TABLE public.community_inventory (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  community_id bigint NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  item_type_id bigint REFERENCES public.inventory_item_types(id) ON DELETE SET NULL,
  custom_name varchar(256),
  quantity integer NOT NULL DEFAULT 1,
  condition varchar(50),
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  -- Either item_type_id or custom_name must be set
  CONSTRAINT inventory_item_name_check CHECK (item_type_id IS NOT NULL OR custom_name IS NOT NULL)
);

ALTER TABLE public.community_inventory ENABLE ROW LEVEL SECURITY;

-- Indexes
CREATE INDEX community_inventory_community_id_idx ON public.community_inventory(community_id);
CREATE INDEX community_inventory_item_type_id_idx ON public.community_inventory(item_type_id);

-- RLS Policies
CREATE POLICY "community_inventory_select_scoped" ON public.community_inventory
  FOR SELECT USING (public.can_access_community(community_id));

CREATE POLICY "community_inventory_insert" ON public.community_inventory
  FOR INSERT WITH CHECK (public.can_manage_brothers(community_id));

CREATE POLICY "community_inventory_update" ON public.community_inventory
  FOR UPDATE USING (public.can_manage_brothers(community_id));

CREATE POLICY "community_inventory_delete" ON public.community_inventory
  FOR DELETE USING (
    public.is_admin()
    OR (created_by = auth.uid() AND public.can_manage_brothers(community_id))
  );

-- Audit trigger
CREATE TRIGGER audit_community_inventory
  AFTER INSERT OR UPDATE OR DELETE ON public.community_inventory
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();
