-- Community visits table for recording visit notes
CREATE TABLE public.community_visits (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  community_id bigint NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  visit_date date NOT NULL DEFAULT CURRENT_DATE,
  description text NOT NULL,
  topics_discussed text,
  visitor_name varchar(256),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.community_visits ENABLE ROW LEVEL SECURITY;

-- Indexes
CREATE INDEX community_visits_community_id_idx ON public.community_visits(community_id);
CREATE INDEX community_visits_visit_date_idx ON public.community_visits(visit_date DESC);

-- RLS Policies
CREATE POLICY "community_visits_select_scoped" ON public.community_visits
  FOR SELECT USING (public.can_access_community(community_id));

CREATE POLICY "community_visits_insert" ON public.community_visits
  FOR INSERT WITH CHECK (public.can_manage_brothers(community_id));

CREATE POLICY "community_visits_update" ON public.community_visits
  FOR UPDATE USING (public.can_manage_brothers(community_id));

CREATE POLICY "community_visits_delete" ON public.community_visits
  FOR DELETE USING (
    public.is_admin()
    OR (created_by = auth.uid() AND public.can_manage_brothers(community_id))
  );

-- Audit trigger
CREATE TRIGGER audit_community_visits
  AFTER INSERT OR UPDATE OR DELETE ON public.community_visits
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();
